name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover tests

    - name: Notify Slack on success or failure
      if: always()
      run: |
        STATUS="FAILED"
        if [ "${{ job.status }}" = "success" ]; then STATUS="PASSED"; fi
        curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"*Python CI* for repo `${{ github.repository }}` on branch `${{ github.ref_name }}` has *${STATUS}* (<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|view run>)\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
